### ISSUE TITLE
Starting Header setting not saved, and not taking affect on output.

### ISSUE THREAD

**Issue by Tam** [selvinortiz/craft.doxter#21] opened 2015-12-10 16:49 UTC
I'm trying to change the starting header to h3, but whenever I save the settings and go back, it's reverted to h1. This is reflected in the code outputted by html(), which outputs h1's instead of h3's.

I've checked the saved settings in the db and `startingHeaderLevel` is set to 3, but this isn't being reflected by the settings or the output.

I've also tried passing the options directly to the html output, but it still has no effect.

Is this something I'm doing wrong, or a bug in the plugin?

**Comment by selvinortiz** [comment] 2015-12-12 17:38
Hi @Tam,
I'll take a look at it this weekend and see if I can reproduce it.

**Comment by selvinortiz** [comment] 2016-07-06 18:04
@Tam The bug your reported about _header level_ has been fixed in `1.3.0`. I couldn't reproduce your issue for a long time, I finally came across it when I had a project that did not use `header anchors`, which caused the level setting to not be applied.

**Closed by selvinortiz** 2016-07-06 18:04 UTC
Labels: bug
