### ISSUE TITLE
Parsing multiple references

### ISSUE THREAD

**Issue by jdsdev** [selvinortiz/craft.doxter#16] opened 2015-06-17 14:20 UTC
Doxter apparently has trouble parsing two back-to-back reference tags.

````
[entry 1]({entry:1:url}) and entry 2

outputs

<a href="link">entry 1</a> and entry 2
````

All good so far. However,

````
[entry 1]({entry:1:url}) and [entry 2]({entry:2:url})

outputs

<a href="entry:1:url">entry 1</a> and <a href="entry:2:url">entry 2</a>
````

No parsing taking place. I solved the issue by turning off Doxter parsing and using the parseRefs Twig filter that's built into Craft, but it would be nice to leave everything in the hands of Doxter.

**Comment by selvinortiz** [comment] 2015-06-17 14:31
Thanks for the heads up!

Somehow I never came across this issues but most likely I never used back to back references. Based on your report, I believe this is a bug caused by a restrictive regular expression.

I'll try to work on this within the next couple of days.

**Comment by pixeljitsu** [comment] 2015-10-27 03:05
Danke.  I don't know what I'd do w/o your plugin. Not huge rush, the lack of iMagick support for PHP7RC is keeping me from using 7 in production anyway.  But I can verify that it us almost 2x faster on my DO Droplet with Craft 2.5.  This morning, I was getting a 242ms total load time for a fresh install of 2.4.2700 which is unreal.  Thanks. :)

**Comment by selvinortiz** [comment] 2015-10-28 07:18
Hey @jdsdev this should have gotten merged a while back and I never updated you on it, sorry about that.

The latest version should support multiple reference tags.

**Closed by selvinortiz** 2015-10-28 07:18 UTC
Labels: bug
